services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d:ro
      - wp_files:/var/www/html:ro
    secrets:
      - ssl_cert
      - ssl_key
    networks:
      - inception-net

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:            ${MYSQL_DATABASE}
      MYSQL_USER:                ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE:  /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE:       /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes:
      - db_data:/var/lib/mysql
      - mariadb_conf:/etc/mysql/mariadb.conf.d:ro
    networks:
      - inception-net

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WP_ADMIN_USER:     ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL:    ${WP_ADMIN_EMAIL}
      WP_SECOND_USER:    ${WP_SECOND_USER}
      WP_SECOND_EMAIL:   ${WP_SECOND_EMAIL}
      DOMAIN_NAME:       ${DOMAIN_NAME}
    volumes:
      - wp_files:/var/www/html
    secrets:
      - mysql_user_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception-net

networks:
  inception-net:
    driver: bridge

volumes:
  db_data:
    driver: local
  wp_files:
    driver: local
  nginx_conf:
    driver: local
  mariadb_conf:
    driver: local

secrets:
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_user_password:
    file: ../secrets/mysql_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ssl_cert:
    file: ../secrets/certs/myCert.crt
  ssl_key:
    file: ../secrets/private/myKey.key
