services:
  nginx:
    build: ./requirements/nginx   # Path to NGINX Dockerfile
    container_name: nginx         # Name assigned to the container
    restart: unless-stopped       # Restart policy on crash or host reboot
    depends_on:
      - wordpress                 # Ensure Wordpress starts before Nginx
    ports:
      - "443:443"                 # Map host port 443 to container port 443 (HTTPS)
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d:ro    # NGINX config files (read-only)
      - /home/nlouis/data/www:/var/www/html:ro            # WordPress files served by NGINX (read-only)
    secrets:
      - ssl_cert
      - ssl_key
    networks:
      - inception-net             # Attach to custom Docker bridge network

  mariadb:
    build:
      context: ./requirements/mariadb  # Path to MariaDB Dockerfile
    container_name: mariadb            # Name assigned to the container
    restart: unless-stopped            # Restart policy on crash or host reboot
    environment:
      MYSQL_DATABASE:      ${MYSQL_DATABASE}       # Database name from .env
      MYSQL_USER:          ${MYSQL_USER}           # App user from .env
    secrets:
      - mysql_root_password
      - mysql_password
    volumes:
      - /home/nlouis/data/db:/var/lib/mysql                       # Persist database data on host
      - ./requirements/mariadb/conf:/etc/mysql/mariadb.conf.d:ro  # MariaDB config (read-only)
    networks:
      - inception-net

  wordpress:
    build:
      context: ./requirements/wordpress   # Path to WordPress Dockerfile
    container_name: wordpress             # Name assigned to the container
    restart: unless-stopped               # Restart policy on crash or host reboot
    depends_on:
      - mariadb                           # Ensure MariaDB starts before WordPress
    environment:
      WORDPRESS_DB_HOST:      mariadb:3306        # Host and port for DB connection
      WORDPRESS_DB_USER:      ${MYSQL_USER}       # DB username from .env
      WORDPRESS_DB_NAME:      ${MYSQL_DATABASE}   # DB name from .env
    volumes:
      - /home/nlouis/data/www:/var/www/html       # Persist WP files on host
    secrets:
      - mysql_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception-net

networks:
  inception-net:
    driver: bridge  # Use Docker's default bridge network driver

secrets:
  mysql_root_password:
    file: ../secrets/db_root_password.txt
  mysql_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ssl_cert:
    file: ../secrets/certs/myCert.crt
  ssl_key:
    file: ../secrets/private/myKey.key
